{
 "title": "AWS App Mesh: Overview",
 "description": "AWS App Mesh Overview",
 "tags": [
  "envoy",
  "aws-appmesh"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Meshed Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(envoy_server_live)" }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Min Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "min(envoy_server_version)" }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m]))"
    }
   ]
  },
  {
   "title": "Total Allocated Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated)"
    }
   ]
  },
  {
   "title": "Unhealthy Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy)  - sum(envoy_cluster_membership_total))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total)-sum(envoy_cluster_membership_healthy)) == bool 0"
    }
   ]
  },
  {
   "title": "Max Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(envoy_server_version)" }
   ]
  },
  {
   "title": "Failures / Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=~\"[5|4]\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Heap Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "Top 5 services by request/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(envoy_http_downstream_rq_total[1m])) by (appmesh_virtual_node))",
     "legendFormat": "{{appmesh_virtual_node}} "
    }
   ]
  },
  {
   "title": "Worst 5 services by HTTP 400 & 500 errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=~\"[5|4]\"}[1m])) by (appmesh_virtual_node))",
     "legendFormat": "{{appmesh_virtual_node}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active)",
     "legendFormat": "Global Connections"
    },
    {
     "expr": "sum(envoy_server_parent_connections)",
     "legendFormat": "Global Parent Connections"
    }
   ]
  },
  {
   "title": "Upstream failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow[1m]))",
     "legendFormat": "Pending Overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m]))",
     "legendFormat": "Connect Timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m]))",
     "legendFormat": "Request Timeout"
    }
   ]
  },
  {
   "title": "Upstream Retries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m]))",
     "legendFormat": "Retry Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow[1m]))",
     "legendFormat": "Retry Overflow"
    }
   ]
  },
  {
   "title": "Envoy xds status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_update_success[1m]))",
     "legendFormat": "Update Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_update_failure[1m]))",
     "legendFormat": "Update Failure"
    }
   ]
  },
  {
   "title": "Global CPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m]))",
     "legendFormat": "Global CPS"
    }
   ]
  },
  {
   "title": "Ingress CPS / RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_rq_total{envoy_http_conn_manager_prefix=\"async-client\"}[1m]))",
     "legendFormat": "Async Client RPS"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "ingress Http CPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "ingress Http RPS"
    }
   ]
  }
 ]
}