{
 "title": "AWS App Mesh: Services",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mesh",
    "label": "Mesh",
    "query": "label_values(envoy_cluster_manager_active_clusters, appmesh_mesh)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(envoy_cluster_manager_active_clusters, app_kubernetes_io_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Meshed Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_server_live{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"})"
    }
   ]
  },
  {
   "title": "Avg Response Latency (p50)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.50, rate(envoy_cluster_upstream_rq_time_bucket{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m])))"
    }
   ]
  },
  {
   "title": "Average Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"})"
    }
   ]
  },
  {
   "title": "Average Traffic Inbound",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Unhealthy Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"})  - sum(envoy_cluster_membership_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}))"
    }
   ]
  },
  {
   "title": "Total Envoy Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"})"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"})-sum(envoy_cluster_membership_healthy{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Avg Response Latency (p99)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(envoy_cluster_upstream_rq_time_bucket{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m])))"
    }
   ]
  },
  {
   "title": "Average Traffic Outbound",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Envoy  Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Traffic (inbound & outbound)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "Outbound (TX)"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "Inbound (RX)"
    }
   ]
  },
  {
   "title": "Ingress HTTP requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(envoy_http_downstream_rq_xx{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\", envoy_http_conn_manager_prefix=\"ingress\"}[1m])) by (envoy_response_code_class))",
     "legendFormat": "HTTP {{envoy_response_code_class}}XX"
    }
   ]
  },
  {
   "title": "Egress HTTP requests/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(envoy_http_downstream_rq_xx{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\", envoy_http_conn_manager_prefix=\"egress\"}[1m])) by (envoy_response_code_class))",
     "legendFormat": "HTTP {{envoy_response_code_class}}XX"
    }
   ]
  },
  {
   "title": "Request Latency (p50)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(envoy_cluster_upstream_rq_time_bucket{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Request Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(envoy_cluster_upstream_rq_time_bucket{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Upstream Request Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "connect timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "pending overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "per try request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_rx_reset{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "request reset"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "destroy initialized from originating service"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_destroy_remote_active_rq{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "destroy initialized from remote service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "request failed maintenance mode"
    }
   ]
  },
  {
   "title": "Upstream Flow Control",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_paused_reading_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "paused reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_resumed_reading_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "resumed reading from destination service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_backed_up_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "paused reading from originating service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_flow_control_drained_total{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "resumed reading from originating service"
    }
   ]
  },
  {
   "title": "Upstream Request Retry",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "request retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "request retry success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{appmesh_mesh=\"$mesh\", appmesh_virtual_node=\"$service\"}[1m]))",
     "legendFormat": "request retry overflow"
    }
   ]
  }
 ]
}